### ISSUE TITLE
Download fails due to NPM latest not being JSON

### ISSUE THREAD

**Issue by rt121212121** [ozelentok/NpmDownloader#1]
Latest package from PyPI, 1.2.0. Python 3.8.4.

```
>>> dl.download("qrcodejs")
[2020-07-18 11:08:59,942] [INFO] Downloading qrcodejs
[2020-07-18 11:08:59,943] [DEBUG] GET https://registry.npmjs.org/qrcodejs/latest
[2020-07-18 11:09:01,648] [ERROR] Failed to get JSON from https://registry.npmjs.org/qrcodejs/latest
[2020-07-18 11:09:01,664] [ERROR] Error downloading qrcodejs
```

![image](https://user-images.githubusercontent.com/32600614/87837540-fca69e80-c8e7-11ea-883f-ecf68ff149df.png)

![image](https://user-images.githubusercontent.com/32600614/87837557-07613380-c8e8-11ea-8372-9ccf721f6dfc.png)

**Comment by ozelentok** [comment]
I believe this was caused by the Cloudflare outage, but the network exception wasn't propagated so it wasn't clear that the outage was the problem.
Exceptions will now be logged as part of the error message, please try again with the new version

**Comment by rt121212121** [comment]
```
>py -3.7-32 -m npmdownloader -f npm-packages.txt -o wwwroot\lib -c 1
[2020-07-24 16:12:10,035] [INFO] Multi Download Started
[2020-07-24 16:12:10,589] [INFO] Downloading bootstrap
[2020-07-24 16:12:10,589] [DEBUG] GET https://registry.npmjs.org/bootstrap/latest
[2020-07-24 16:12:10,624] [INFO] Downloading qrcode
[2020-07-24 16:12:10,624] [DEBUG] GET https://registry.npmjs.org/qrcode/latest
[2020-07-24 16:12:12,224] [ERROR] Failed to get JSON from https://registry.npmjs.org/qrcode/latest
Traceback (most recent call last):
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 989, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1017, in _create_connection_transport
    await waiter
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\sslproto.py", line 530, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\npmdownloader\npmclient.py", line 22, in _get_json
    async with self._session.get(url) as response:
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\client.py", line 483, in _request
    timeout=real_timeout
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 939, in _wrap_create_connection
    req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host registry.npmjs.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')]
[2020-07-24 16:12:12,228] [ERROR] Error downloading qrcode
Traceback (most recent call last):
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 989, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1017, in _create_connection_transport
    await waiter
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\sslproto.py", line 530, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\npmdownloader\packagedownloader.py", line 21, in _download_single_package
    version = await self._client.get_package_latest_version(name)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\npmdownloader\npmclient.py", line 29, in get_package_latest_version
    return (await self.get_registry_package_info(name, 'latest'))['version']
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\npmdownloader\npmclient.py", line 38, in get_registry_package_info
    return await self._get_json(utils.build_version_url(name, version))
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\npmdownloader\npmclient.py", line 22, in _get_json
    async with self._session.get(url) as response:
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\client.py", line 483, in _request
    timeout=real_timeout
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 939, in _wrap_create_connection
    req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host registry.npmjs.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')]
[2020-07-24 16:12:12,272] [ERROR] Failed to get JSON from https://registry.npmjs.org/bootstrap/latest
Traceback (most recent call last):
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 989, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1017, in _create_connection_transport
    await waiter
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\sslproto.py", line 530, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\npmdownloader\npmclient.py", line 22, in _get_json
    async with self._session.get(url) as response:
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\client.py", line 483, in _request
    timeout=real_timeout
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 939, in _wrap_create_connection
    req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host registry.npmjs.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')]
[2020-07-24 16:12:12,276] [ERROR] Error downloading bootstrap
Traceback (most recent call last):
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 989, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1017, in _create_connection_transport
    await waiter
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\sslproto.py", line 530, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\npmdownloader\packagedownloader.py", line 21, in _download_single_package
    version = await self._client.get_package_latest_version(name)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\npmdownloader\npmclient.py", line 29, in get_package_latest_version
    return (await self.get_registry_package_info(name, 'latest'))['version']
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\npmdownloader\npmclient.py", line 38, in get_registry_package_info
    return await self._get_json(utils.build_version_url(name, version))
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\npmdownloader\npmclient.py", line 22, in _get_json
    async with self._session.get(url) as response:
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\client.py", line 483, in _request
    timeout=real_timeout
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "C:\Users\rt12\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\connector.py", line 939, in _wrap_create_connection
    req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host registry.npmjs.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')]
[2020-07-24 16:12:12,318] [INFO] Multi Download Finished
```

**Comment by ozelentok** [comment]
>SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired

It seems you're receiving an expired SSL certificate from the NPM registry server, which is very odd, as the date on your machine looks fine and on my machine I'm receiving a valid certificate:
> *  subject: CN=ssl891738.cloudflaressl.com
> *  start date: May 19 00:00:00 2020 GMT
> *  expire date: Nov 25 23:59:59 2020 GMT
> *  subjectAltName: host "registry.npmjs.org" matched cert's "*.npmjs.org"
> *  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2

It's possible your machine isn't updated and the problem lies in old CA certificates installed on your machine.
Try browsing to https://registry.npmjs.org with different browsers and see if the problem occurs there as well

**Comment by rt121212121** [comment]
Edge Firefox and Chrome all show the same JSON file and give no hint of cert problems.

**Comment by ozelentok** [comment]
So it's either a bug in aiohttp or something wrong with the python installation, run these two scripts, at least one should fail
```python
import urllib.request

with urllib.request.urlopen('https://registry.npmjs.org/qrcodejs/latest') as response:
    print(len(response.read()))
```

```python
import aiohttp
import asyncio


async def test_aiohttp():
    async with aiohttp.ClientSession() as session:
        async with session.get('https://registry.npmjs.org/qrcodejs/latest') as response:
            print(len(await response.text()))


loop = asyncio.get_event_loop()
loop.run_until_complete(test_aiohttp())
```

**Comment by rt121212121** [comment]
Both fail.

**Comment by ozelentok** [comment]
This issue sounds similar to yours
https://stackoverflow.com/questions/62141402/how-can-i-verify-my-ssl-certificate-for-discord
